import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "¡Feliz aniversario!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" style={{ height: '100%' }}>
      <body
        style={{
          margin: 0,
          minHeight: '100vh',
          backgroundColor: '#FFF0F6',
        }}
      >
        <Providers>
          <div
            style={{
              minHeight: '100vh',
              display: 'flex',
              flexDirection: 'column',
            }}
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}